title = "Nurofsun"
publishDir = "public"
staticDir = "assets"
enableEmoji = true
pygmentsUseClasses = true
buildDrafts = true

[params]
 featuredImage = "site-featured-image.png" 
 logo = "logo.png"
 author = "Nurahmat"
 github = "https://github.com/nurofsun"
 twitter = "@nurofsun"
 subtitle = "Front-End Web Developer & Graphic Designer"
 description = "Build Your Business With Creativity and Code"
 metaDescription = "Looking for a new tips about web development? you're in the right place because it's free, and become a great developer."
 copyright = "Nurofsun's Blog"

[menu]
  [[menu.main]]
    identifier = "blog"
    title = "Blog"
    name = "Blog"
    url = "/blog"
  [[menu.main]]
    identifier = "contact"
    title = "Contact"
    name = "Contact"
    url = "/contact"

[permalinks]
   blog = "/:slug/"

[outputs]
  home = ["HTML", "JSON", "RSS"]

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
