baseURL = "http://localhost:1313"
title = "Nurofsun"

buildDrafts = true
publishDir = "public"
staticDir = "assets"

enableEmoji = true
enableRobotsTXT = true
canonifyURLs = true
pygmentsUseClasses = true

[params]
 featuredImage = "site-featured-image.png" 
 logo = "logo.png"
 author = "Nurahmat"
 github = "https://github.com/nurofsun"
 twitter = "@nurofsun"
 subtitle = "Modern Web Development Tips for Free"
 description = "Learn about web development free and fun"
 metaDescription = "Looking for a new tips about web development? you're in the right place because it's free, and become a great developer."
 copyright = "Nurofsun's Blog"

[menu]
  [[menu.main]]
    identifier = "blog"
    title = "Blog"
    name = "Blog"
    url = "/blog"
  [[menu.main]]
    identifier = "about"
    title = "About"
    name = "About"
    url = "/about"
  [[menu.main]]
    identifier = "contact"
    title = "Contact"
    name = "Contact"
    url = "/contact"

[permalinks]
   blog = "/:slug/"

[outputs]
  home = ["HTML", "JSON", "RSS"]

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
